subjects: [1,2,3,4,5,6,7,8]
grasps:
  - 'rest'
  - 'tripod'
  - 'lateral'
  - 'pointer'
  - 'power'
block_configuration:
  "+": [2, 4, 5, 6, 8]
  "x": [1, 3, 5, 7, 9]
trials: 5
days:
  - 1
  - 2
blocks:
  - 1
  - 2
NO_TRIALS: 5
GLOBAL_REC_TRIALS: 150
window_size: 256
stride: 100
stride2: 10
offset_correction: True
save_path: "hudgins256_100" # "processed_data\hudgins256_100"
feat_extract_alg: 'hudgins_feats'
data_save_format: '{trial_key}_{counter}_{int(temp_lbl)}_{position}'